import {SlashCommandBuilder} from 'discord.js';
export const emojiCommands=[
new SlashCommandBuilder().setName('add-emoji').setDescription('Add custom server emoji').addStringOption(o=>o.setName('name').setDescription('Emoji name').setRequired(true).setMinLength(2).setMaxLength(32)).addAttachmentOption(o=>o.setName('image').setDescription('PNG/JPG/GIF/WEBP').setRequired(true)),
new SlashCommandBuilder().setName('rename-emoji').setDescription('Rename server emoji').addStringOption(o=>o.setName('emoji').setDescription('Emoji name or ID').setRequired(true)).addStringOption(o=>o.setName('name').setDescription('New name').setRequired(true).setMinLength(2).setMaxLength(32)),
new SlashCommandBuilder().setName('delete-emoji').setDescription('Delete server emoji').addStringOption(o=>o.setName('emoji').setDescription('Emoji name or ID').setRequired(true)).addBooleanOption(o=>o.setName('confirm').setDescription('Confirm permanent deletion').setRequired(true)),
new SlashCommandBuilder().setName('emoji-list').setDescription('List custom server emojis')];
async function find(g,q){await g.emojis.fetch();const id=q.replace(/\D/g,'');return g.emojis.cache.get(id)||g.emojis.cache.find(e=>e.name?.toLowerCase()===q.toLowerCase());}
export async function handleEmojis(i){
if(i.commandName==='add-emoji'){const n=i.options.getString('name',true),a=i.options.getAttachment('image',true);if(!['image/png','image/jpeg','image/gif','image/webp'].includes(a.contentType))return i.reply({content:'❌ Upload PNG, JPG, GIF, or WEBP.',ephemeral:true});await i.deferReply({ephemeral:true});const e=await i.guild.emojis.create({attachment:a.url,name:n,reason:`Added by ${i.user.tag} via Atomic Builder`});return i.editReply(`✅ Added ${e} as **:${e.name}:**`);}
if(i.commandName==='rename-emoji'){const e=await find(i.guild,i.options.getString('emoji',true));if(!e)return i.reply({content:'❌ Emoji not found.',ephemeral:true});const old=e.name;await e.setName(i.options.getString('name',true));return i.reply({content:`✅ Renamed **:${old}:** → ${e}`,ephemeral:true});}
if(i.commandName==='delete-emoji'){if(!i.options.getBoolean('confirm',true))return i.reply({content:'❌ Nothing deleted.',ephemeral:true});const e=await find(i.guild,i.options.getString('emoji',true));if(!e)return i.reply({content:'❌ Emoji not found.',ephemeral:true});const n=e.name;await e.delete();return i.reply({content:`✅ Deleted **:${n}:**.`,ephemeral:true});}
if(i.commandName==='emoji-list'){await i.guild.emojis.fetch();const es=[...i.guild.emojis.cache.values()];return i.reply({content:es.length?`😀 **Server emojis (${es.length})**\n${es.slice(0,100).map(e=>`${e} **:${e.name}:**`).join('\n')}`:'This server has no custom emojis yet.',ephemeral:true});}return false;}
