import {SlashCommandBuilder,ChannelType} from 'discord.js';import {getGuildSettings,setGuildSettings} from '../utils/storage.js';
const def='Welcome {mention} to **{server}**! 🎉';
function render(t,m){return t.replaceAll('{mention}',`<@${m.id}>`).replaceAll('{user}',m.user.username).replaceAll('{server}',m.guild.name).replaceAll('{count}',String(m.guild.memberCount));}
export const welcomeCommands=[
new SlashCommandBuilder().setName('welcome-setup').setDescription('Configure automatic welcomes').addChannelOption(o=>o.setName('channel').setDescription('Welcome channel').addChannelTypes(ChannelType.GuildText).setRequired(true)).addStringOption(o=>o.setName('message').setDescription('Use {mention}, {user}, {server}, {count}').setRequired(true).setMaxLength(1800)).addBooleanOption(o=>o.setName('dm').setDescription('Also DM the new member')).addRoleOption(o=>o.setName('role').setDescription('Optional role to give new members')),
new SlashCommandBuilder().setName('welcome-test').setDescription('Preview configured welcome'),
new SlashCommandBuilder().setName('welcome-disable').setDescription('Disable automatic welcomes')];
export async function handleWelcome(i){
if(i.commandName==='welcome-setup'){const c=i.options.getChannel('channel',true),msg=i.options.getString('message',true),dm=i.options.getBoolean('dm')??false,r=i.options.getRole('role');await setGuildSettings(i.guild.id,{welcome:{enabled:true,channelId:c.id,message:msg,dm,roleId:r?.id||null}});return i.reply({content:`✅ Welcome enabled in ${c}.\n**Preview:** ${render(msg,i.member)}`,ephemeral:true});}
if(i.commandName==='welcome-test'){const c=(await getGuildSettings(i.guild.id)).welcome;if(!c?.enabled)return i.reply({content:'❌ Use `/welcome-setup` first.',ephemeral:true});return i.reply({content:`🧪 **Preview**\n${render(c.message||def,i.member)}\n\nDM: **${c.dm?'On':'Off'}**${c.roleId?` • Auto-role: <@&${c.roleId}>`:''}`,ephemeral:true});}
if(i.commandName==='welcome-disable'){await setGuildSettings(i.guild.id,{welcome:{enabled:false}});return i.reply({content:'✅ Automatic welcomes disabled.',ephemeral:true});}return false;}
export async function handleMemberJoin(m){const c=(await getGuildSettings(m.guild.id)).welcome;if(!c?.enabled)return;const msg=render(c.message||def,m),ch=await m.guild.channels.fetch(c.channelId).catch(()=>null);if(ch?.isTextBased())await ch.send({content:msg,allowedMentions:{users:[m.id]}}).catch(()=>{});if(c.roleId){const r=await m.guild.roles.fetch(c.roleId).catch(()=>null);if(r)await m.roles.add(r,'Atomic Builder welcome auto-role').catch(()=>{});}if(c.dm)await m.send(msg).catch(()=>{});}
